name: nim_core_v2_platform_interface
description: A common platform interface for the nim_core_v2 plugin.
version: 10.3.1
homepage: https://github.com/netease-kit/NIM-Flutter-SDK
repository: https://github.com/netease-kit/NIM-Flutter-SDK


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1
  universal_io: ^2.0.4
  universal_html: ^2.2.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^6.8.0
