name: nim_core
description: A Flutter plugin for NetEase IM SDK on Android, iOS and Windows.
version: 1.7.7
homepage: https://github.com/netease-kit/NIM-Flutter-SDK
# remove before publish
#publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  nim_core_platform_interface:
#     '>=1.7.7 <1.8.0'
    path: ../nim_core_platform_interface
  nim_core_windows:
#    ^1.0.8
    path: ../nim_core_windows
  nim_core_macos:
#    ^1.0.8
    path: ../nim_core_macos
  nim_core_web:
#   ^1.0.2
     path: ../nim_core_web
  path_provider: ^2.0.2
  # yunxin_base: ^0.1.0-rc.0
  universal_io: ^2.0.4
  yunxin_alog: ^2.0.0
  hawk_meta: ^0.0.1
#    path: ../../auto_test/hawk_meta

dev_dependencies:
  flutter_test:
    sdk: flutter
  permission_handler: ^10.0.0
  hawk_source_gen: ^0.0.1
#    path: ../../auto_test/hawk_source_gen
  build_runner:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.netease.nimflutter
        pluginClass: NimCorePlugin
      ios:
        pluginClass: NimCorePlugin
      windows:
        default_package: nim_core_windows
      macos:
        default_package: nim_core_macos
      web:
        default_package: nim_core_web

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
